# Generated by Django 5.0 on 2023-12-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("in_patient", "0002_rooms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rooms",
            name="room_number",
            field=models.IntegerField(unique=True),
        ),
    ]
