# Generated by Django 5.0 on 2023-12-17 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("in_patient", "0003_alter_rooms_room_number"),
        ("patient", "0012_nurse"),
    ]

    operations = [
        migrations.AddField(
            model_name="inpatientmanagement",
            name="assigned_nurse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="patient.nurse",
            ),
        ),
        migrations.AlterField(
            model_name="inpatientmanagement",
            name="room_number",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="in_patient.rooms",
            ),
        ),
    ]
