# Generated by Django 5.0 on 2023-12-17 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("in_patient", "0004_inpatientmanagement_assigned_nurse_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inpatientmanagement",
            name="scheduled_surgery_date",
        ),
        migrations.RemoveField(
            model_name="inpatientmanagement",
            name="scheduled_surgery_room",
        ),
        migrations.RemoveField(
            model_name="inpatientmanagement",
            name="surgery_booked",
        ),
        migrations.RemoveField(
            model_name="surgeryschedule",
            name="room_number",
        ),
        migrations.AddField(
            model_name="surgeryschedule",
            name="scheduled_surgery_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="surgeryschedule",
            name="scheduled_surgery_room",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="in_patient.rooms",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="surgeryschedule",
            name="surgery_booked",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="rooms",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("Shared", "Shared"),
                    ("Private", "Private"),
                    ("Surgery", "Surgery"),
                ],
                max_length=10,
            ),
        ),
    ]
