# Generated by Django 5.0 on 2023-12-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "in_patient",
            "0005_remove_inpatientmanagement_scheduled_surgery_date_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="inpatientmanagement",
            name="bed_booked_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inpatientmanagement",
            name="bed_remove_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
