# Generated by Django 5.0 on 2023-12-17 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("in_patient", "0007_alter_inpatientmanagement_patient"),
        ("patient", "0013_alter_appointment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="surgeryschedule",
            name="patient",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="patient.patient",
            ),
            preserve_default=False,
        ),
    ]
