# Generated by Django 5.0 on 2023-12-17 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("in_patient", "0008_surgeryschedule_patient"),
        ("patient", "0014_surgeon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surgeryschedule",
            name="surgeon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="patient.surgeon"
            ),
        ),
    ]
