# Generated by Django 5.0 on 2023-12-15 03:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="email",
            field=models.CharField(default=99799, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patient",
            name="phone_no",
            field=models.CharField(default="jay@gmail.com", max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="patient",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], max_length=1
            ),
        ),
    ]
