# Generated by Django 5.0 on 2023-12-15 03:23

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0002_patient_email_patient_phone_no_alter_patient_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="contact_number",
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="doctor",
            name="email",
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="doctor",
            name="specialization",
            field=models.CharField(
                default=datetime.datetime(
                    2023, 12, 15, 3, 23, 34, 783724, tzinfo=datetime.timezone.utc
                ),
                max_length=100,
            ),
            preserve_default=False,
        ),
    ]
