# Generated by Django 5.0 on 2023-12-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0004_appointment_reason_appointment_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
