# Generated by Django 5.0 on 2023-12-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0005_appointment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[("B", "Booked"), ("P", "Pending")], default="B", max_length=1
            ),
        ),
    ]
