# Generated by Django 5.0 on 2023-12-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0006_alter_appointment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[("Booked", "Booked"), ("Booked", "Pending")],
                default=("Booked", "Booked"),
                max_length=10,
            ),
        ),
    ]
