# Generated by Django 5.0 on 2023-12-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0007_alter_appointment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[("B", "Booked"), ("P", "Pending")],
                default="Booked",
                max_length=1,
            ),
        ),
    ]
