# Generated by Django 5.0 on 2023-12-15 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0009_patienthistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="patienthistory",
            name="appointment",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="patient.appointment",
            ),
            preserve_default=False,
        ),
    ]
