# Generated by Django 5.0 on 2023-12-16 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0010_patienthistory_appointment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[("B", "Booked"), ("P", "Pending"), ("C", "Completed")],
                default="Booked",
                max_length=1,
            ),
        ),
    ]
