# Generated by Django 5.0 on 2023-12-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0012_nurse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Booked", "Booked"),
                    ("Pending", "Pending"),
                    ("Completed", "Completed"),
                ],
                default="Booked",
                max_length=20,
            ),
        ),
    ]
