# Generated by Django 5.0 on 2023-12-17 00:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StaffMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("date_of_birth", models.DateField()),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("Doctor", "Doctor"),
                            ("Nurse", "Nurse"),
                            ("Surgeon", "Surgeon"),
                            ("Physician Assistant", "Physician Assistant"),
                            ("Pharmacist", "Pharmacist"),
                            ("Medical Technologist", "Medical Technologist"),
                            ("Radiologist", "Radiologist"),
                            ("Physical Therapist", "Physical Therapist"),
                            ("Occupational Therapist", "Occupational Therapist"),
                            (
                                "Speech-Language Pathologist",
                                "Speech-Language Pathologist",
                            ),
                            ("Administrative Staff", "Administrative Staff"),
                            (
                                "Maintenance and Support Staff",
                                "Maintenance and Support Staff",
                            ),
                        ],
                        max_length=100,
                    ),
                ),
                ("department", models.CharField(max_length=255)),
                ("employee_id", models.CharField(max_length=10, unique=True)),
                ("shift_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("schedule_job_shift", models.BooleanField(default=False)),
                ("ssn", models.CharField(blank=True, max_length=11, null=True)),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("qualifications", models.TextField(blank=True, null=True)),
                (
                    "license_certification",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "experience_years",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("blood_type", models.CharField(blank=True, max_length=5, null=True)),
                ("allergies", models.TextField(blank=True, null=True)),
                ("medical_conditions", models.TextField(blank=True, null=True)),
                ("joining_date", models.DateField()),
                ("status", models.CharField(default="Active", max_length=10)),
                ("termination_date", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
