# Generated by Django 5.0 on 2023-12-17 00:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staffmember",
            name="department",
        ),
        migrations.RemoveField(
            model_name="staffmember",
            name="employee_id",
        ),
        migrations.RemoveField(
            model_name="staffmember",
            name="schedule_job_shift",
        ),
        migrations.AlterField(
            model_name="staffmember",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Non_Acive", "Non_Acive"),
                    ("Holiday", "Holiday"),
                ],
                max_length=10,
            ),
        ),
    ]
