# Generated by Django 5.0 on 2023-12-17 01:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0002_remove_staffmember_department_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffmember",
            name="specialization",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
